### ISSUE TITLE
What's Qt version

### ISSUE THREAD

**Issue by duhuandi** [Combitech/libqtazureiot#1]
hello ,I meet some questions in you code 
../libqtazureiot/libqtazureiot.so: undefined reference to `json_object_get_string'
../libqtazureiot/libqtazureiot.so: undefined reference to `json_value_free'
../libqtazureiot/libqtazureiot.so: undefined reference to `json_value_get_object'
../libqtazureiot/libqtazureiot.so: undefined reference to `json_parse_string'
I think them are beause the version of Qt?

**Comment by Dillonsixsixsix** [comment]
> hello ,I meet some questions in you code
> ../libqtazureiot/libqtazureiot.so: undefined reference to `json_object_get_string' ../libqtazureiot/libqtazureiot.so: undefined reference to `json_value_free'
> ../libqtazureiot/libqtazureiot.so: undefined reference to `json_value_get_object' ../libqtazureiot/libqtazureiot.so: undefined reference to `json_parse_string'
> I think them are beause the version of Qt?
